viamrobotics/slam

- .github/workflows/main.yml
- .github/workflows/pullrequest.yml
- .github/workflows/test.yml
- slam-libraries/Makefile
- slam-libraries/viam-cartographer/README.md
- slam-libraries/viam-cartographer/scripts/setup_cartographer.sh
- slam-libraries/viam-cartographer/src/slam_service/config.h
This ensures we don't run orbslam tests when only cartographer files have changed and vice versa. After this change, we can make the "Format", "Build and Test Orbslam", and "Build and Test Cartographer" jobs required for merge. If one of these doesn't run (because the code didn't change), that shouldn't prevent merge.
> [DATA-580] Set up a github action to build cartographer and add make targets

- slam-libraries/viam-cartographer/CMakeLists.txt
- slam-libraries/viam-cartographer/scripts/run_cartographer.sh
- slam-libraries/viam-cartographer/src/main.cc
- slam-libraries/viam-cartographer/src/slam_service/config.cc
Together with https://github.com/viamrobotics/rdk/pull/1507, this lets us run cartographer through rdk.
> [DATA-567] Support running cartographer through rdk

- slam-libraries/Makefile
- slam-libraries/viam-orb-slam3/CMakeLists.txt
- slam-libraries/viam-orb-slam3/orbslam_server_v1_test.cc
- slam-libraries/viam-orb-slam3/setup_orbslam_macos.sh
Together with https://github.com/viamrobotics/ORB_SLAM3/pull/5, this adds support for building on mac. There will be another PR to add the brew package, and then maybe a third for a CI job that uses the brew package.
> [DATA-605] Support building on osx

- slam-libraries/viam-cartographer/src/io/read_PCD_file.cc
- slam-libraries/viam-cartographer/src/main.cc
- slam-libraries/viam-cartographer/src/mapping/map_builder.cc
- slam-libraries/viam-cartographer/src/mapping/map_builder.h
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
https://viam.atlassian.net/browse/DATA-609
This took less time than I thought, thanks to the work that had already been done! I tested both online and offline processing using data generated through rdk. I tested on a raspberry pi with the rplidar server running. I used this config for online (modified for offline):
```
{
"services": [{
"name": "testcarto",
"type": "slam",
"attributes": 
{
"algorithm": "cartographer",
"sensors": ["rplidar"],
"config_params": {
"mode": "2d",
"v": "1"
},
"data_dir": "$HOME/carto-data"
}}],
"network": {
"bind_address": "0.0.0.0:8080"
},
"remotes": [{
"address": "localhost:4444",
"name": "lidar",
"prefix": false
}]
}
```
Cartographer was able to process the data and respond to `GetMap` requests.
> [DATA-609] Add live ingestion loop

- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
https://viam.atlassian.net/browse/DATA-733
**Situation:** The user chooses `map_rate_sec = 0` - which technically means running SLAM in localization action mode - but no map is found in the `data/map` folder.
**Previous behavior:** Run SLAM in mapping mode (since no map is found) but don't save maps (since `map_rate_sec == 0`).
**New behavior:** Throw an error, since we assume the user wants to run SLAM in localization mode but we can't find a map to localize on.
**Tested on:**
* 2.4 GHz 8-Core Intel Core i9; macOS Monterey
> [DATA-733] Throw error if no map is found

- slam-libraries/viam-cartographer/src/mapping/map_builder.cc
- slam-libraries/viam-cartographer/src/mapping/map_builder.h
- slam-libraries/viam-cartographer/src/slam_service/config.cc
- slam-libraries/viam-cartographer/src/slam_service/config_test.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
Ticket: https://viam.atlassian.net/browse/DATA-117
Done:
* Read optimize_on_start parameter from config parameters and use that to decide whether or not an uploaded map should be optimized before using it
* Rename: `offlineFlag` --> `offline_flag` for consistency
> [DATA-117] Read optimize_on_start parameter from config_params

- slam-libraries/viam-cartographer/src/io/file_handler.cc
- slam-libraries/viam-cartographer/src/main.cc
- slam-libraries/viam-cartographer/src/mapping/map_builder.cc
- slam-libraries/viam-cartographer/src/slam_service/config.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/utils/slam_service_helpers.cc
Ticket: https://viam.atlassian.net/browse/RSDK-1044
* `VLOG(1)` is used for debug-level logging. Disabled by default (`v = 0`). Enable by setting `v = 1`.
* `LOG(...)` is used for info, warning, error, and fatal logging. It is not advised to change the setting for this since some of the functionalities (e.g. port forwarding) rely on obtaining the logs.
More information: https://github.com/google/glog#setting-flags
> [RSDK-1044] Adjust log levels

- slam-libraries/viam-cartographer/src/main.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1_main.cc
Currently the slam algorithms fail to shut down when rdk attempts to close them. This PR attempts to update the exit handler to safely close out of the slam algorithms, based off information found in[ this PR](https://github.com/viamrobotics/goutils/pull/116). Will have a followup PR in rdk to clean up the integration test code
Note the changes make the clean shutdown occur only when running the slam servers with rdk. Running the binaries standalone/without managed process controlling them is not a behavior we need to support. 
https://viam.atlassian.net/browse/RSDK-1255
[RSDK-1255]: https://viam.atlassian.net/browse/RSDK-1255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-1255] fix slam process exit handler

- slam-libraries/viam-cartographer/src/slam_service/config.cc
- slam-libraries/viam-cartographer/src/slam_service/config_test.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
- slam-libraries/viam-orb-slam3/orbslam_server_v1.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1.h
- slam-libraries/viam-orb-slam3/orbslam_server_v1_main.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1_test.cc
Adds a new argument, 'use_live_data' to SLAM, defined in the [SLAM usability scope doc](https://docs.google.com/document/d/1RsT-c0QOtkMKa-rwUGY0-emUmKIRSaO3mzT1v6MtFjk/edit?usp=sharing), that is responsible for indicating if newly generated data or previously generated data should be used during this run. This is replacing the previous offlineFlag that was auto populated based on the presence or lack of sensors. 
This PR is made in conjunction with the PR in RDK that adds use_live_data both to the list of arguments passed to SLAM but also the configs in testing.
In order to ensure backwards compatibility currently in orbslam we check if the use_live_data argument exists and if not, we use the old method of the sensor list to determine online/offline mode for cartographer we currently over …
> [RSDK-1038] Adding use_live_data parameter to SLAM

- slam-libraries/viam-cartographer/src/slam_service/config.cc
- slam-libraries/viam-cartographer/src/slam_service/config_test.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1_test.cc
This PR removes the associated code and test cases that allowed backwards compatibility between offline/online mode being determined by the `sensors` list (old) vs the `use_live_data` parameter (new). This PR will be merged after the RDK PR associated with `use_live_data` has been merged.
Associated PR: [#1729](https://github.com/viamrobotics/rdk/pull/1729)
JIRA Ticket: [RSDK-1625](https://viam.atlassian.net/browse/RSDK-1625)
[RSDK-1625]: https://viam.atlassian.net/browse/RSDK-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-1625 Remove Backwards Compatibility with use_live_data

- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
This PR adds the `GetPositionNew` endpoint to cartographer. This `GetPositionNew` will eventually replace the current `GetPosition`. It differs from `GetPosition` in two of its return parameters:
- Instead of returning a `PoseInFrame` it now returns a `Pose`
- There is an additional string return (`component_reference`) that represents the component that should be used to connect the SLAM outputs to RDK's proprioceptive reference frame system.
JIRA Ticket: [RSDK-1073](https://viam.atlassian.net/browse/RSDK-1073)
Note: Tested using dev branch in cartographer integration tests. Will add tests in once the dev parameter PR is submitted and we are ready to start testing endpoints.
[RSDK-1073]: https://viam.atlassian.net/browse/RSDK-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> RSDK-1073 Add GetPositionNew to Cartographer

- slam-libraries/Makefile
- slam-libraries/viam-orb-slam3/orbslam_server_v1.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1.h
[Ticket](https://viam.atlassian.net/browse/RSDK-1061)
Implements viam.service.slam.v1.SLAMService/GetPositionNew on orbslamv3 slam library.
How to see the output:
```bash
grpcurl -d '{"name": "slam"}'  -plaintext -protoset <(~/slam-clone/slam-libraries/grpc/bin/buf build -o -) $(sudo netstat -tulpn | grep LISTEN | grep orb_grpc_serv | awk '{print $4}' | sort | head -n 1) viam.service.slam.v1.SLAMService/GetPositionNew
{
"pose": {
"x": 0.007205881178379059,
"y": -0.004640873987227678,
"z": 0.021260758861899376
},
"componentReference": "color",
"extra": {
"quat": {
"imag": 0.009775514714419842,
"jmag": 0.006308149080723524,
"kmag": -0.010251480154693127,
"real": 0.999879777431488
}
}
}
```
> RSDK-1061 [orb] GetPositionNew

- slam-libraries/viam-cartographer/src/mapping/map_builder.cc
- slam-libraries/viam-cartographer/src/mapping/map_builder.h
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
This PR allows for the on-demand serialization of the internal state (.pbstream) of cartographer. This can then be saved to a file and loaded into a subsequent cartographer run. Currently addition PRs are in the work to do this for OrbSLAM, adding the GetInternalState endpoint to RDK and including GetInternalState tests to the integration testing scripts.
JIRA Ticket: [RSDK-1075](https://viam.atlassian.net/browse/RSDK-1075)
RDK PR/ Cartographer Testing (adding GetInternalState): [PR #1776](https://github.com/viamrobotics/rdk/pull/1776)
Notes:
The implementation in this PR utilizes a file interface to access the data and sent it over grpc to RDK. This is no ideal as it contains a file read and write. However, this is hard to get away from which I found after about 6 hours of research. …
> RSDK-1075 [carto] Add GetInternalState

- slam-libraries/viam-orb-slam3/orbslam_server_v1.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1.h
- slam-libraries/viam-orb-slam3/orbslam_server_v1_main.cc
[Ticket](https://viam.atlassian.net/browse/RSDK-1062)
Add GetPointCloudMap GRPC endpoint to orbslam.
Tested via:
```bash
grpcurl -d '{"name": "run-slam"}'  -plaintext -protoset <(~/slam-clone/slam-libraries/grpc/bin/buf build -o -) $(sudo netstat -tulpn | grep LISTEN | grep orb_grpc_se | awk '{print $4}' | sort | head -n 1) viam.service.slam.v1.SLAMService/GetPointCloudMap | jq -r '.pointCloudPcd' | base64 -d > get_point_cloud_map.pcd
grpcurl -d '{"name": "run-slam", "mime_type": "pointcloud/pcd"}'  -plaintext -protoset <(~/slam-clone/slam-libraries/grpc/bin/buf build -o -) $(sudo netstat -tulpn | grep LISTEN | grep orb_grpc_ | awk '{print $4}' | sort | head -n 1) viam.service.slam.v1.SLAMService/GetMap | jq -r '.pointCloud.pointCloud' | base64 -d > get_map.pcd
#convert new & old response …
```
> [RSDK-1062] implement orb GetPointCloudMap

- .gitmodules
submodule links made the reppo unable to retrieve the submodules unless there was an ssh key in use with github. In addition the ssh links would cause the brew packages to fail on systems without an ssh key.
ticket: https://viam.atlassian.net/browse/RSDK-1816
> [RSDK-1816] update submodules to use http links instead of ssh 

- slam-libraries/viam-orb-slam3/orbslam_server_v1.cc
- slam-libraries/viam-orb-slam3/orbslam_server_v1.h
- slam-libraries/viam-orb-slam3/orbslam_server_v1_main.cc
[Ticket](https://viam.atlassian.net/browse/RSDK-1063)
NOTE: Depending on approval of the scope doc to make GetInternalState & GetPointCloudMap server streaming endpoints, this PR may need a follow-up PR to refactor into a server streaming API before considering the ticket complete. 
Tested with:
```bash
grpcurl -max-msg-sz 320000000  -d '{"name": "run-slam"}'  -plaintext -protoset <(~/slam-clone/slam-libraries/grpc/bin/buf build -o -) $(sudo netstat -tulpn | grep LISTEN | grep orb_grpc_serv | awk '{print $4}' | sort | head -n 1) viam.service.slam.v1.SLAMService/GetInternalState | jq -r '.internalState' | base64 -d > orb_internal_state.osa
```
Depends on https://github.com/viamrobotics/ORB_SLAM3/pull/7 to add `DumpOsa` to `ORB_SLAM3::System`
Testing steps (from @JohnN193  thank you!):
``` …
```
> Rsdk 1063 implement orb GetInternalState

- slam-libraries/Makefile
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
Part 1 of several on [RSDK-1955](https://viam.atlassian.net/browse/RSDK-1955?atlOrigin=eyJpIjoiYjdmMjUwYTJlNzM2NDNiNzk1MTM0M2JmMWY2NDJhZWIiLCJwIjoiaiJ9) This implements `GetInternalStateStream` for the cartographer grpc server. Additionally adds `GetPointCloudMapStream` as unimplemented
Tested using grpcurl and the script to extract chunks from the output that Nick wrote. I made a `GetInternalStateStream` request and formatted the `pbstream` to be injected into cartographer. Cartographer was able to use the internal state.
TESTING:
Tested using this [dataset]( https://drive.google.com/file/d/1w9l4XzJwyKXXgWs8XIhKgIlhzAv6UlMU/view?usp=share_link)
run running viam-server using this [robot](https://app.viam.com/robot?id=2fda0155-ee9c-4f6e-a08f-588796da2ee2&tab=config%2Cservices) 
after run …
> [RSDK-1955] Add GetInternalStateStream to cartographer

- slam-libraries/viam-cartographer/CMakeLists.txt
- slam-libraries/viam-cartographer/scripts/setup_cartographer_macos.sh
This PR solves a minor problem involving openssl when installing Cartographer for the first time on a mac.
JIRA Ticket: [RSDK-1970](https://viam.atlassian.net/browse/RSDK-1970)
[RSDK-1970]: https://viam.atlassian.net/browse/RSDK-1970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-1970 Cartographer First Time Install Issues on MacOS

- slam-libraries/viam-cartographer/lua_files/locating_in_map.lua
- slam-libraries/viam-cartographer/lua_files/mapping_new_map.lua
- slam-libraries/viam-cartographer/lua_files/updating_a_map.lua
- slam-libraries/viam-cartographer/src/slam_service/slam_service.cc
- slam-libraries/viam-cartographer/src/slam_service/slam_service.h
Ticket: https://viam.atlassian.net/browse/RSDK-1753
* Fixes localization mode and updating mode
Works decently well with an A3 and the following config:
```json
{
"services": [
{
"name": "run-online-slam-test",
"model": "cartographer",
"type": "slam",
"attributes": {
"port": "localhost:8083",
"data_dir": "YOUR_DATA_DIRECTORY",
"delete_processed_data": true,
"use_live_data": true,
"map_rate_sec": 0,
"sensors": [
"rplidar"
],
"config_params": {
"optimize_on_start": "true",
"num_range_data": "100",
"mode": "2d",
"max_submaps_to_keep": "2"
}
}
}
],
"modules": [
{
"name": "rplidar_module",
"executable_path": "/usr/local/bin/rplidar-module"
}
],
"components": [
{
"depends_on": [],
"model": "viam:lidar:rplidar",
"attributes": {
"device_path": "/dev/tty.SLAB_USBtoUART"
},
"name": "rplidar", …
```
> RSDK-1753 - Fix localization mode

- slam-libraries/Makefile
- slam-libraries/viam-cartographer/CMakeLists.txt
- slam-libraries/viam-cartographer/cartographer_build_utils/CMakeLists.txt
- slam-libraries/viam-cartographer/scripts/build_cartographer.sh
- slam-libraries/viam-cartographer/scripts/build_viam_cartographer.sh
- slam-libraries/viam-cartographer/src/main.cc
- Define `ABSL_LEGACY_THREAD_ANNOTATIONS` in CMake pipeline so cartographer continues to build with absl version `20230125.1` and greater: https://github.com/abseil/abseil-cpp/releases.
I've tested this by running:
```bash
make cartoclean && make buf && make buildcarto && make installcarto
```
It compiles just fine on both.
I then ran cartogropher in mapping / updating mode on both mac & linux with those compiled grpc servers & they appeared to work on both platforms. I updated the map for about 5 min & rendered the map in the RDK control UI.
> Define ABSL_LEGACY_THREAD_ANNOTATIONS

- config/config.go
- config/config_test.go
This PR removes the dev flag from the config/json. The associated PR (https://github.com/viamrobotics/rdk/pull/2014) will be merged first and will remove all uses of it from the slam service.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-1684
> RSDK-1684 Remove dev from Config

- go.mod
- utils/utils.go
- utils/utils_test.go
Ticket: https://viam.atlassian.net/browse/RSDK-2336
Moves the following from rdk into the slam repo:
* https://github.com/viamrobotics/rdk/blob/main/services/slam/builtin/builtin_helpers.go
* https://github.com/viamrobotics/rdk/blob/main/services/slam/builtin/builtin_helpers_test.go
Blocks related PR in RDK: https://github.com/viamrobotics/rdk/pull/2060
> RSDK-2336 - [rdk -> slam] Move builtin_helpers into utils

- config/config.go
- config/config_test.go
Remove the unused dev flag in SLAM Map Representation project. Similar edits were also made in the rdk, viam-cartographer, and viam-orb-slam3 repos, see associated PR.
JIRA Ticket: https://viam.atlassian.net/browse/RSDK-2435
Associated PRs: 
- https://github.com/viamrobotics/rdk/pull/2150
- https://github.com/viamrobotics/viam-orb-slam3/pull/34
- https://github.com/viamrobotics/viam-cartographer/pull/37
> RSDK-2435 Remove Dev Flag
